swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /api/v1.0

schemes:
  - http

consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /transactions/:
    get:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: billing.api.views.transaction
      responses:
        200:
          description: greeting response
          examples:
            "text/plain": "Hello John"